-- MySQL Script generated by MySQL Workbench
-- Tue Aug 28 15:27:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema USTG_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema USTG_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `USTG_BD` DEFAULT CHARACTER SET utf8 ;
USE `USTG_BD` ;

-- -----------------------------------------------------
-- Table `USTG_BD`.`Reservista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`Reservista` (
  `IdReservista` INT NOT NULL AUTO_INCREMENT,
  `NomeGuerra` VARCHAR(25) NULL,
  `Profissao` VARCHAR(40) NULL,
  `LocalTrabalho` VARCHAR(40) NULL,
  `Escolaridade` VARCHAR(40) NULL,
  `Voluntario` BLOB NULL,
  `Religiao` VARCHAR(40) NULL,
  `Folgas` INT NULL,
  `Status` VARCHAR(40) NULL,
  `Patente` BLOB NULL,
  `Ingressao` VARCHAR(20) NULL,
  PRIMARY KEY (`IdReservista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`EscalaDeGuarda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`EscalaDeGuarda` (
  `IdEscalaDeGuarda` INT NOT NULL AUTO_INCREMENT,
  `Reservista_IdReservista` INT NOT NULL,
  `DataDaGuarda` VARCHAR(45) NULL,
  PRIMARY KEY (`IdEscalaDeGuarda`, `Reservista_IdReservista`),
  INDEX `fk_EscalaDeGuarda_Reservista1_idx` (`Reservista_IdReservista` ASC),
  CONSTRAINT `fk_EscalaDeGuarda_Reservista1`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`ControleDeFalta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`ControleDeFalta` (
  `IdControleDeFalta` INT NOT NULL AUTO_INCREMENT,
  `Reservista_IdReservista` INT NOT NULL,
  `Data` DATE NULL,
  `Presenca` BLOB NULL,
  PRIMARY KEY (`IdControleDeFalta`, `Reservista_IdReservista`),
  INDEX `fk_ControleDeFalta_Reservista1_idx` (`Reservista_IdReservista` ASC),
  CONSTRAINT `fk_ControleDeFalta_Reservista1`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`TAF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`TAF` (
  `IdTaf` INT NOT NULL AUTO_INCREMENT,
  `Reservista_IdReservista` INT NOT NULL,
  `Data` DATE NULL,
  `Barra` INT NULL,
  `Flexao` INT NULL,
  `Abdominal` INT NULL,
  `Corrida` INT NULL,
  `Final` VARCHAR(10) NULL,
  INDEX `fk_TAF_Reservista1_idx` (`Reservista_IdReservista` ASC),
  PRIMARY KEY (`IdTaf`),
  CONSTRAINT `fk_TAF_Reservista1`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`TempoDeServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`TempoDeServico` (
  `Reservista_IdReservista` INT NOT NULL,
  `HoraExtra` DOUBLE NULL,
  `TotalHora` DOUBLE NULL,
  PRIMARY KEY (`Reservista_IdReservista`),
  INDEX `fk_TempoDeServico_Reservista1_idx` (`Reservista_IdReservista` ASC),
  CONSTRAINT `fk_TempoDeServico_Reservista1`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`Servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`Servidor` (
  `IdServidor` INT NOT NULL AUTO_INCREMENT,
  `NomeCompleto` VARCHAR(60) NULL,
  `Login` VARCHAR(20) NULL,
  `Senha` VARCHAR(20) NULL,
  PRIMARY KEY (`IdServidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`DataDisponivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`DataDisponivel` (
  `IdDataDisponivel` INT NOT NULL,
  `Reservista_IdReservista` INT NOT NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`IdDataDisponivel`, `Reservista_IdReservista`),
  INDEX `fk_DataDisponivel_Reservista1_idx` (`Reservista_IdReservista` ASC),
  CONSTRAINT `fk_DataDisponivel_Reservista1`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`DataIndisponivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`DataIndisponivel` (
  `IdDataIndisponivel` INT NOT NULL AUTO_INCREMENT,
  `Reservista_IdReservista` INT NOT NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`IdDataIndisponivel`, `Reservista_IdReservista`),
  INDEX `fk_DataIndisponivel_Reservista1_idx` (`Reservista_IdReservista` ASC),
  CONSTRAINT `fk_DataIndisponivel_Reservista1`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`DadosDomicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`DadosDomicilio` (
  `Reservista_IdReservista` INT NOT NULL,
  `Endereco` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `CidadeNatal` VARCHAR(45) NULL,
  PRIMARY KEY (`Reservista_IdReservista`),
  INDEX `fk_C_Reservista_idx` (`Reservista_IdReservista` ASC),
  CONSTRAINT `fk_C_Reservista`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`DadosContato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`DadosContato` (
  `Reservista_IdReservista` INT NOT NULL,
  `TelefoneFixo` VARCHAR(20) NULL,
  `TelefoneCelular` VARCHAR(20) NULL,
  `Email` VARCHAR(50) NULL,
  PRIMARY KEY (`Reservista_IdReservista`),
  CONSTRAINT `fk_Contato_Reservista1`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`DadosDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`DadosDocumento` (
  `Reservista_IdReservista` INT NOT NULL,
  `RA` VARCHAR(30) NULL,
  `Identidade` VARCHAR(20) NULL,
  `CPF` VARCHAR(20) NULL,
  `TituloEleitoral` VARCHAR(20) NULL,
  PRIMARY KEY (`Reservista_IdReservista`),
  UNIQUE INDEX `RA_UNIQUE` (`RA` ASC),
  UNIQUE INDEX `Identidade_UNIQUE` (`Identidade` ASC),
  UNIQUE INDEX `TituloEleitoral_UNIQUE` (`TituloEleitoral` ASC),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  CONSTRAINT `fk_Documento_Reservista1`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`DadosPessoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`DadosPessoal` (
  `Reservista_IdReservista` INT NOT NULL,
  `NomeCompleto` VARCHAR(60) NULL,
  `DataNascimento` VARCHAR(20) NULL,
  `NomeMae` VARCHAR(60) NULL,
  `NomePai` VARCHAR(60) NULL,
  PRIMARY KEY (`Reservista_IdReservista`),
  CONSTRAINT `fk_DadosPessoal_Reservista1`
    FOREIGN KEY (`Reservista_IdReservista`)
    REFERENCES `USTG_BD`.`Reservista` (`IdReservista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
