-- MySQL Script generated by MySQL Workbench
-- Tue Aug 21 19:13:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema USTG_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema USTG_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `USTG_BD` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `USTG_BD` ;

-- -----------------------------------------------------
-- Table `USTG_BD`.`Reservista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`Reservista` (
  `IdReservista` INT NOT NULL AUTO_INCREMENT,
  `NomeGuerra` VARCHAR(40) NULL,
  `NomeCompleto` VARCHAR(60) NULL,
  `RA` VARCHAR(20) NULL,
  `DataNascimento` VARCHAR(20) NULL,
  `CidadeNatal` VARCHAR(50) NULL,
  `Identidade` VARCHAR(20) NULL,
  `CPF` VARCHAR(20) NULL,
  `TituloEleitoral` VARCHAR(20) NULL,
  `NomeMae` VARCHAR(60) NULL,
  `NomePai` VARCHAR(60) NULL,
  `Endereco` VARCHAR(60) NULL,
  `TelefoneFixo` VARCHAR(20) NULL,
  `TelefoneCelular` VARCHAR(20) NULL,
  `Email` VARCHAR(50) NULL,
  `Profissao` VARCHAR(40) NULL,
  `LocalTrabalho` VARCHAR(40) NULL,
  `Escolaridade` VARCHAR(40) NULL,
  `Voluntario` BLOB NULL,
  `Religiao` VARCHAR(40) NULL,
  `Folgas` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `Modalidade` VARCHAR(45) NULL,
  PRIMARY KEY (`IdReservista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`EscalaDeGuarda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`EscalaDeGuarda` (
  `IdEscalaDeGuarda` INT NOT NULL AUTO_INCREMENT,
  `DataDaGuarda` VARCHAR(45) NULL,
  PRIMARY KEY (`IdEscalaDeGuarda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`ControleDeFalta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`ControleDeFalta` (
  `IdControleDeFalta` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdControleDeFalta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`TesteDeAptidaoFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`TesteDeAptidaoFisica` (
  `IdTesteDeAptidaoFisica` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdTesteDeAptidaoFisica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`TempoDeServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`TempoDeServico` (
  `IdTempoDeServico` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdTempoDeServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTG_BD`.`Servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTG_BD`.`Servidor` (
  `IdServidor` INT NOT NULL AUTO_INCREMENT,
  `NomeCompleto` VARCHAR(60) NULL,
  `Login` VARCHAR(20) NULL,
  `Senha` VARCHAR(20) NULL,
  PRIMARY KEY (`IdServidor`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
